List<Map> productsList = [
  {
    'id': 0,
    'image': 'https://picsum.photos/250?image=9',
    'Currency': 'EGP',
    'price': 73,
    'price_dot': 25,
    'counter_buy': '35',
    'rating': '4.6',
    'describtion': 'USB 2.0 الي Mini Sata II',
    'isFavorite': false,
    'isCart': false,
  },
  {
    'id': 1,
    'image':
        'http://www.shadowsphotography.co/wp-content/uploads/2017/12/photography-01-800x400.jpg',
    'Currency': 'EGP',
    'price': 18,
    'price_dot': 12,
    'counter_buy': '2',
    'rating': '2.6',
    'describtion':
        'كاميرا تصوير عاليه الجوده hd كاميرا تصوير فيديو  hd كاميرا تصوير فيديو hd كاميرا تصوير فيديو ',
    'isFavorite': false,
    'isCart': false,
  },
  {
    'id': 2,
    'image': 'https://picsum.photos/250?image=9',
    'Currency': 'EGP',
    'price': 73,
    'price_dot': 23,
    'counter_buy': '35',
    'rating': '4.6',
    'describtion': 'USB 2.0 الي Mini Sata II',
    'isFavorite': false,
    'isCart': false,
  },
  {
    'id': 3,
    'image':
        'http://www.shadowsphotography.co/wp-content/uploads/2017/12/photography-01-800x400.jpg',
    'Currency': 'EGP',
    'price': 21,
    'price_dot': 33,
    'counter_buy': '2',
    'rating': '2.6',
    'describtion': 'كاميرا تصوير عاليه الجوده hd كاميرا تصوير فيديو ',
    'isFavorite': false,
    'isCart': false,
  },
  {
    'id': 4,
    'image':
        'http://www.shadowsphotography.co/wp-content/uploads/2017/12/photography-01-800x400.jpg',
    'Currency': 'EGP',
    'price': 102,
    'price_dot': 07,
    'counter_buy': '2',
    'rating': '2.6',
    'describtion': 'كاميرا تصوير عاليه الجوده hd كاميرا تصوير فيديو ',
    'isFavorite': false,
    'isCart': false,
  },
];
